### ISSUE TITLE
Hello, can I reproduce this code if my computer only has a 4070Ti?

### ISSUE THREAD

**Issue by hljWmh** [cvlab-stonybrook/Large-Image-Diffusion#5]

**Comment by hljWmh** [comment]
Also I have a question, this method synthesizes a large image, does it randomly pick a patch to generate and then merge it, or does it generate multiple patches and then synthesize a large image?

**Comment by srikarym** [comment]
We train our models on 6 48GB GPUs. You could probably use gradient checkpointing if you have fewer GPUs.
To generate a large image, we generate multiple 256x256 patches and then merge them.

**Comment by hljWmh** [comment]
Does the input condition have to contain text?Why is it that I run the code and it comes back with a dimension mismatch on my own dataset, my original pathology image is in .svs format.

Traceback (most recent call last):
  File "main.py", line 719, in <module>
    trainer.fit(model, data)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 553, in fit
    self._run(model)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 918, in _run
    self._dispatch()
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 996, in run_stage
    return self._run_train()
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1045, in _run_train
    self.fit_loop.run()
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\epoch\training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 101, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 148, in advance
    result = self._run_optimization(batch_idx, split_batch, opt_idx, optimizer)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 202, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 396, in _optimizer_step
    model_ref.optimizer_step(
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\core\lightning.py", line 1618, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\core\optimizer.py", line 209, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\core\optimizer.py", line 129, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 292, in optimizer_step
    make_optimizer_step = self.precision_plugin.pre_optimizer_step(
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\plugins\precision\native_amp.py", line 59, in pre_optimizer_step
    result = lambda_closure()
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 236, in _training_step_and_backward_closure
    result = self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, hiddens)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 537, in training_step_and_backward
    result = self._training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\loops\batch\training_batch_loop.py", line 307, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 172, in training_step
    return self.model.training_step(*args, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\models\diffusion\ddpm.py", line 406, in training_step
    loss, loss_dict = self.shared_step(batch)
  File "D:\wmh\Large-Image-Diffusion\ldm\models\diffusion\ddpm.py", line 995, in shared_step
    loss = self(x, c)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\models\diffusion\ddpm.py", line 1007, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\models\diffusion\ddpm.py", line 1160, in p_losses
    model_output = self.apply_model(x_noisy, t, cond)
  File "D:\wmh\Large-Image-Diffusion\ldm\models\diffusion\ddpm.py", line 1131, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\models\diffusion\ddpm.py", line 1834, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 817, in forward
    h = module(h, emb, context)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\diffusionmodules\openaimodel.py", line 85, in forward
    x = layer(x, context)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\attention.py", line 340, in forward
    x = block(x, context=context[i])
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\attention.py", line 273, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\attention.py", line 278, in _forward
    x = self.attn2(self.norm2(x), context=context) + x
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\attention.py", line 174, in forward
    q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> (b h) n d', h=h), (q, k, v))
  File "D:\wmh\Large-Image-Diffusion\ldm\modules\attention.py", line 174, in <lambda>
    q, k, v = map(lambda t: rearrange(t, 'b n (h d) -> (b h) n d', h=h), (q, k, v))
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\einops\einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
  File "C:\Users\PC\.conda\envs\ldm\lib\site-packages\einops\einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b n (h d) -> (b h) n d".
 Input tensor shape: torch.Size([1, 1, 11848, 384]). Additional info: {'h': 1}.
 Wrong shape: expected 3 dims. Received 4-dim tensor.

**Comment by srikarym** [comment]
Our condition is an embedding extracted from an SSL encoder, not text. Can you take a look at our [sample data](https://github.com/cvlab-stonybrook/Large-Image-Diffusion/blob/main/notebooks/dataset_samples/brca_hipt_patches.pickle)?

**Comment by hljWmh** [comment]
OK, Thank you
